Test/pr branch (#3)
pr-workflow fix

diff --git a/.github/workflows/PR-VERIFICATION.yml b/.github/workflows/PR-VERIFICATION.yml
--- a/.github/workflows/PR-VERIFICATION.yml
+++ b/.github/workflows/PR-VERIFICATION.yml
@@ -2,9 +2,13 @@ name: PR-VERIFICATION
 
 on:
   pull_request:
+    types: [opened, synchronize]
 
 jobs:
   BUILD:
+
+    permissions:
+      checks: write
 
     defaults:
       run:
@@ -12,18 +16,35 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
+
+      - name: Verify Branch Name
+        run: |
+          
+            PR_BRANCH=${{ github.head_ref }}
+            
+            BRANCH_PATTERN="test\/[A-Za-z0-9]*"
+            
+            if [[ ! "$PR_BRANCH" =~ $BRANCH_PATTERN ]]; then
+              echo "Error: Branch name '$PR_BRANCH' does not match the required pattern."
+              exit 1
+            else
+              echo "Branch name '$PR_BRANCH' is valid."
+            fi
+
       - name: CHECKOUT
         uses: actions/checkout@v3
 
-      - name: CHECK BRANCH NAME
-        working-directory: ./hooks
-        run : |
-          chmod +x ./pre-commit
-          ./pre-commit
-
       - name: EXECUTE TESTS
         run : |
+          chmod +x ./gradlew
           ./gradlew clean test
+
+      - name: ATTACH ARTIFACT
+        if: success()
+        uses: actions/upload-artifact@v4
+        with:
+          name: my-artifact
+          path: '**/build/reports/tests/test'
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
